spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/data?useSSL=true
    username: root
    password: sz7228318
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
server:
  port: 8081